# prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'prom_marvin'

rule_files:
  - 'alert.rules'
  - 'backup.rules'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['testprometheus:9090']
  - job_name: 'node'
    static_configs:
      - targets: ['testnodeexporter:9100']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['testcadvisor:8080']
  - job_name: 'pushgateway'
    static_configs:
      - targets: ['pushgateway:9091']
